/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clavicom_gui_mouse_UIMouse */

#ifndef _Included_clavicom_gui_mouse_UIMouse
#define _Included_clavicom_gui_mouse_UIMouse
#ifdef __cplusplus
extern "C" {
#endif
#undef clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSABLE_UNKNOWN
#define clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSABLE_DEFAULT
#define clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSABLE_SET
#define clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSABLE_SET 2L
#undef clavicom_gui_mouse_UIMouse_TOP_ALIGNMENT
#define clavicom_gui_mouse_UIMouse_TOP_ALIGNMENT 0.0f
#undef clavicom_gui_mouse_UIMouse_CENTER_ALIGNMENT
#define clavicom_gui_mouse_UIMouse_CENTER_ALIGNMENT 0.5f
#undef clavicom_gui_mouse_UIMouse_BOTTOM_ALIGNMENT
#define clavicom_gui_mouse_UIMouse_BOTTOM_ALIGNMENT 1.0f
#undef clavicom_gui_mouse_UIMouse_LEFT_ALIGNMENT
#define clavicom_gui_mouse_UIMouse_LEFT_ALIGNMENT 0.0f
#undef clavicom_gui_mouse_UIMouse_RIGHT_ALIGNMENT
#define clavicom_gui_mouse_UIMouse_RIGHT_ALIGNMENT 1.0f
#undef clavicom_gui_mouse_UIMouse_serialVersionUID
#define clavicom_gui_mouse_UIMouse_serialVersionUID -7644114512714619750i64
#undef clavicom_gui_mouse_UIMouse_serialVersionUID
#define clavicom_gui_mouse_UIMouse_serialVersionUID 4613797578919906343i64
#undef clavicom_gui_mouse_UIMouse_INCLUDE_SELF
#define clavicom_gui_mouse_UIMouse_INCLUDE_SELF 1L
#undef clavicom_gui_mouse_UIMouse_SEARCH_HEAVYWEIGHTS
#define clavicom_gui_mouse_UIMouse_SEARCH_HEAVYWEIGHTS 1L
#undef clavicom_gui_mouse_UIMouse_NOT_OBSCURED
#define clavicom_gui_mouse_UIMouse_NOT_OBSCURED 0L
#undef clavicom_gui_mouse_UIMouse_PARTIALLY_OBSCURED
#define clavicom_gui_mouse_UIMouse_PARTIALLY_OBSCURED 1L
#undef clavicom_gui_mouse_UIMouse_COMPLETELY_OBSCURED
#define clavicom_gui_mouse_UIMouse_COMPLETELY_OBSCURED 2L
#undef clavicom_gui_mouse_UIMouse_WHEN_FOCUSED
#define clavicom_gui_mouse_UIMouse_WHEN_FOCUSED 0L
#undef clavicom_gui_mouse_UIMouse_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define clavicom_gui_mouse_UIMouse_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef clavicom_gui_mouse_UIMouse_WHEN_IN_FOCUSED_WINDOW
#define clavicom_gui_mouse_UIMouse_WHEN_IN_FOCUSED_WINDOW 2L
#undef clavicom_gui_mouse_UIMouse_UNDEFINED_CONDITION
#define clavicom_gui_mouse_UIMouse_UNDEFINED_CONDITION -1L
#undef clavicom_gui_mouse_UIMouse_IS_DOUBLE_BUFFERED
#define clavicom_gui_mouse_UIMouse_IS_DOUBLE_BUFFERED 0L
#undef clavicom_gui_mouse_UIMouse_ANCESTOR_USING_BUFFER
#define clavicom_gui_mouse_UIMouse_ANCESTOR_USING_BUFFER 1L
#undef clavicom_gui_mouse_UIMouse_IS_PAINTING_TILE
#define clavicom_gui_mouse_UIMouse_IS_PAINTING_TILE 2L
#undef clavicom_gui_mouse_UIMouse_IS_OPAQUE
#define clavicom_gui_mouse_UIMouse_IS_OPAQUE 3L
#undef clavicom_gui_mouse_UIMouse_KEY_EVENTS_ENABLED
#define clavicom_gui_mouse_UIMouse_KEY_EVENTS_ENABLED 4L
#undef clavicom_gui_mouse_UIMouse_FOCUS_INPUTMAP_CREATED
#define clavicom_gui_mouse_UIMouse_FOCUS_INPUTMAP_CREATED 5L
#undef clavicom_gui_mouse_UIMouse_ANCESTOR_INPUTMAP_CREATED
#define clavicom_gui_mouse_UIMouse_ANCESTOR_INPUTMAP_CREATED 6L
#undef clavicom_gui_mouse_UIMouse_WIF_INPUTMAP_CREATED
#define clavicom_gui_mouse_UIMouse_WIF_INPUTMAP_CREATED 7L
#undef clavicom_gui_mouse_UIMouse_ACTIONMAP_CREATED
#define clavicom_gui_mouse_UIMouse_ACTIONMAP_CREATED 8L
#undef clavicom_gui_mouse_UIMouse_CREATED_DOUBLE_BUFFER
#define clavicom_gui_mouse_UIMouse_CREATED_DOUBLE_BUFFER 9L
#undef clavicom_gui_mouse_UIMouse_IS_PRINTING
#define clavicom_gui_mouse_UIMouse_IS_PRINTING 11L
#undef clavicom_gui_mouse_UIMouse_IS_PRINTING_ALL
#define clavicom_gui_mouse_UIMouse_IS_PRINTING_ALL 12L
#undef clavicom_gui_mouse_UIMouse_IS_REPAINTING
#define clavicom_gui_mouse_UIMouse_IS_REPAINTING 13L
#undef clavicom_gui_mouse_UIMouse_WRITE_OBJ_COUNTER_FIRST
#define clavicom_gui_mouse_UIMouse_WRITE_OBJ_COUNTER_FIRST 14L
#undef clavicom_gui_mouse_UIMouse_RESERVED_1
#define clavicom_gui_mouse_UIMouse_RESERVED_1 15L
#undef clavicom_gui_mouse_UIMouse_RESERVED_2
#define clavicom_gui_mouse_UIMouse_RESERVED_2 16L
#undef clavicom_gui_mouse_UIMouse_RESERVED_3
#define clavicom_gui_mouse_UIMouse_RESERVED_3 17L
#undef clavicom_gui_mouse_UIMouse_RESERVED_4
#define clavicom_gui_mouse_UIMouse_RESERVED_4 18L
#undef clavicom_gui_mouse_UIMouse_RESERVED_5
#define clavicom_gui_mouse_UIMouse_RESERVED_5 19L
#undef clavicom_gui_mouse_UIMouse_RESERVED_6
#define clavicom_gui_mouse_UIMouse_RESERVED_6 20L
#undef clavicom_gui_mouse_UIMouse_WRITE_OBJ_COUNTER_LAST
#define clavicom_gui_mouse_UIMouse_WRITE_OBJ_COUNTER_LAST 21L
#undef clavicom_gui_mouse_UIMouse_REQUEST_FOCUS_DISABLED
#define clavicom_gui_mouse_UIMouse_REQUEST_FOCUS_DISABLED 22L
#undef clavicom_gui_mouse_UIMouse_INHERITS_POPUP_MENU
#define clavicom_gui_mouse_UIMouse_INHERITS_POPUP_MENU 23L
#undef clavicom_gui_mouse_UIMouse_OPAQUE_SET
#define clavicom_gui_mouse_UIMouse_OPAQUE_SET 24L
#undef clavicom_gui_mouse_UIMouse_AUTOSCROLLS_SET
#define clavicom_gui_mouse_UIMouse_AUTOSCROLLS_SET 25L
#undef clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define clavicom_gui_mouse_UIMouse_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     clavicom_gui_mouse_UIMouse
 * Method:    InitMouseHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_clavicom_gui_mouse_UIMouse_InitMouseHook
  (JNIEnv *, jobject);

/*
 * Class:     clavicom_gui_mouse_UIMouse
 * Method:    FinishMouseHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_clavicom_gui_mouse_UIMouse_FinishMouseHook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
