/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clavicom_gui_engine_click_ClickEngine */

#ifndef _Included_clavicom_gui_engine_click_ClickEngine
#define _Included_clavicom_gui_engine_click_ClickEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clavicom_gui_engine_click_ClickEngine
 * Method:    InitMouseHook
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_clavicom_gui_engine_click_ClickEngine_InitMouseHook
  (JNIEnv *, jobject, jint);

/*
 * Class:     clavicom_gui_engine_click_ClickEngine
 * Method:    FinishMouseHook
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_clavicom_gui_engine_click_ClickEngine_FinishMouseHook
  (JNIEnv *, jobject);

/*
 * Class:     clavicom_gui_engine_click_ClickEngine
 * Method:    InhibitMouseHook
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_clavicom_gui_engine_click_ClickEngine_InhibitMouseHook
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
